### ISSUE TITLE
What is the second script?

### ISSUE THREAD

**Issue by AdrienLemaire** [c-okelly/org_to_anki#67]
The README states

> Provides two command line scripts. First is to upload an org or txt files to Anki. The second allow quick notetaking and storage.

But [Command line scripts](https://github.com/c-okelly/org_to_anki#command-line-scripts) only lists org_to_anki, so I'm wondering about that other notetaking and storage script.

I'm still wondering whether it's worth adopting your plugin or not. Used to rst/markdown syntax, but org seems like a fair alternative.
It also seems like a vim plugin could be wrapped around org_to_anki, to upload a file selection (eg a `:ToAnki` mapping).

How much effort would it take to support the reverse process, Anki to org? If I could sync Anki with a git repo of .org files, it would be extremely satisfying (the git repo could then be used as part of a Zettelkasten).

**Comment by c-okelly** [comment]
Hey,

Unfortunately that script no longer works and I had forgotten to remove mention of it from the readme. It only every functioned as a CLI capture tool where you could run it to get user input that would then be written to a file stored somewhere on the users local system.

I'm not really familiar with vim plugins as all but in theory there is nothing to stop you you calling the script with some contextual arguments to parse the current file. (I assume!)

I'm not sure. I would definitely think it is possible in future but the upload does not store any metadata about where the files came from.  It would be similar to an "Export Deck" feature another user has actually requested. It would be doable I think but I'm really not sure on the time scale of when I might get such a thing done.

I think the next big change on the backlog will be to allow users to sync rather then just update. So that changes in files are reflected in the users' decks

**Comment by c-okelly** [comment]
Please feel free to follow #65 for updates on when the sync behavior will be implemented!
