### ISSUE TITLE
Non-Technical Help Request

### ISSUE THREAD

**Issue by AAO2020** [c-okelly/org_to_anki#73]
Hi,

I do not have a technical error or inquiry.
I have a very a basic issue that I have spent a lot of time trying to resolve.

I installed your add-on in Anki.
I created a basic test file, then copied the steps in your "Word or LibreOffice files" page.
It worked the first time around when I imported into Anki, then it stopped working when I tried again.
So I downloaded LibreOffice and converted the test file into an HTML.
However, every time I try to import something it asks me to fill out "Import Options" and "Field Mapping".
I have no idea what I am supposed to fill out as there is not really any guidance. When I fill it out, etc, it gives me flash cards with gibberish.

I have no error report
I am a Windows 10 user

Please advise.
Thank you,
Ben

**Comment by c-okelly** [comment]
Hey Ben,

It sounds like you are potentially using the wrong import menu.

I assume you are clicking here?

![Wrong import](https://user-images.githubusercontent.com/8889083/83907839-e919ec80-a71a-11ea-9eff-9602ccdefbf0.png)

This is the correct menu:

![Right menu](https://user-images.githubusercontent.com/8889083/83907858-f33beb00-a71a-11ea-9386-c6fc1e4621d0.png)

The File > Import is the built in Anki way to handle imports and completed different from normal imports

**Comment by AAO2020** [comment]
Thanks!
Such a simple fix... I was trying to figure it out on my own. Thanks again!

**Comment by c-okelly** [comment]
The answer is always simple when you know it! I think the docs could probably be clearer tbh

**Comment by AAO2020** [comment]
On another note, why does the HTML file from a Word document differ from a HTML file from a Libre document?
I am wondering. Not a technical user. Just an every day Joe.

**Comment by AAO2020** [comment]
Also, this does not work for either Libre or Word.

Multi-level files

Question with sublists
A question
   Group 1
      Item A
      Item B
   Group 2
      Item C
      Item D

**Comment by c-okelly** [comment]
> On another note, why does the HTML file from a Word document differ from a HTML file from a Libre document?

As for the why I could not even being to guess but the TLDR of the situation is as follows:  

Microsoft word generates a html file where the contents of the document look correct but are generally not using standard html syntax to actually render the format. The best example of this is the list syntax where it just inserts icons and white spacing to what looks like a list to the users.

In comparison LibreOffice generates "proper" html syntax that is much easier to parse into metadata so that I can generate a card.

I'm sure there is some legacy reason why word is doing this. Word will also generate different html / file encoding depending on what system is is run from. It also re-encodes the entire html file if you open and save it. It just ended up being to much hassle and I really don't think I'm going to support it in future

**Comment by c-okelly** [comment]
Can you send me a screen shot of the list and possible and attach the html file and I will have a look.

I assume you are using bullet points in the LibreOffice document? As from above I would not advise using Word as it will likely just throw errors

**Comment by AAO2020** [comment]
Hi,
Please see attached for Libre Writer document and associated HTML file.
Let me know.
Thanks
________________________________

**Comment by c-okelly** [comment]
I'm not sure you are able to attach files to the actual github issues.

You can either pastebin them or email me at okellyconor at gmail.com

**Comment by c-okelly** [comment]
Fixed offline
